import frappe

def setup():
    print("Applying Refinements...")
    try:
        rename_crm_workspace()
        refine_print_format()
        frappe.db.commit()
        print("Refinements Applied Successfully!")
    except Exception as e:
        frappe.db.rollback()
        print(f"Refinements Failed: {e}")
        import traceback
        traceback.print_exc()

def rename_crm_workspace():
    # Attempt to find the CRM workspace
    if frappe.db.exists("Workspace", "CRM"):
        print("Renaming CRM Workspace to Consulting Services...")
        if not frappe.db.exists("Workspace", "Consulting Services"):
            frappe.rename_doc("Workspace", "CRM", "Consulting Services", force=True)
    elif frappe.db.exists("Workspace", "Consulting Services"):
         print("Workspace already renamed to Consulting Services.")
    else:
        print("Workspace 'CRM' not found.")

def refine_print_format():
    print("Refining Print Format...")
    pf_name = "Techxle Bilingual"
    if not frappe.db.exists("Print Format", pf_name):
        print(f"Print Format {pf_name} not found.")
        return

    logo_path = "/files/techxle_logo.jpg" 
    
    # Enhanced HTML with Techxle Blue (#003366) and better structure
    html = f"""
<div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; direction: ltr; color: #333;">
    
    <!-- Header -->
    <div style="border-bottom: 3px solid #003366; padding-bottom: 20px; margin-bottom: 20px;">
        <table style="width: 100%; border: none;">
            <tr>
                <td style="width: 20%; vertical-align: top;">
                    <img src="{logo_path}" style="max-width: 100%; max-height: 80px;">
                </td>
                <td style="width: 80%; text-align: right; vertical-align: top;">
                    <h1 style="color: #003366; margin: 0;">{{{{ doc.company }}}}</h1>
                    <h3 style="margin: 5px 0 0; color: #555;">{{{{ doc.doctype }}}} / {{{{ doc.doctype == 'Sales Invoice' and 'فاتورة المبيعات' or 'عرض سعر' }}}}</h3>
                    <p style="margin: 5px 0 0; font-size: 12px;">{{{{ doc.name }}}}</p>
                </td>
            </tr>
        </table>
    </div>

    <!-- Data Table -->
    <table class="table table-bordered" style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
        <thead>
            <tr style="background-color: #003366; color: white;">
                <th style="padding: 10px; border: 1px solid #003366; width: 5%;">Sr<br>م</th>
                <th style="padding: 10px; border: 1px solid #003366; width: 45%;">Item / Description<br>الصنف / الوصف</th>
                <th style="padding: 10px; border: 1px solid #003366; width: 15%; text-align: right;">Qty<br>الكمية</th>
                <th style="padding: 10px; border: 1px solid #003366; width: 15%; text-align: right;">Rate<br>السعر</th>
                <th style="padding: 10px; border: 1px solid #003366; width: 20%; text-align: right;">Amount<br>المبلغ</th>
            </tr>
        </thead>
        <tbody>
            {{% for item in doc.items %}}
            <tr>
                <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">{{{{ loop.index }}}}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">
                    <b style="color: #003366;">{{{{ item.item_code }}}}</b><br>
                    {{{{ item.description }}}}
                </td>
                <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">{{{{ item.qty }}}}</td>
                <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">{{{{ item.get_formatted("rate") }}}}</td>
                <td style="padding: 8px; border: 1px solid #ddd; text-align: right;">{{{{ item.get_formatted("amount") }}}}</td>
            </tr>
            {{% endfor %}}
        </tbody>
        <tfoot>
            <tr style="background-color: #f9f9f9;">
                <td colspan="4" style="padding: 10px; border: 1px solid #ddd; text-align: right;"><b>Total / المجموع</b></td>
                <td style="padding: 10px; border: 1px solid #ddd; text-align: right; color: #003366; font-weight: bold;">
                    {{{{ doc.get_formatted("grand_total") }}}}
                </td>
            </tr>
            <tr>
                 <td colspan="5" style="padding: 15px; border: 1px solid #ddd;">
                    <strong style="color: #003366;">In Words:</strong> {{{{ doc.in_words }}}}
                 </td>
            </tr>
        </tfoot>
    </table>
    
    <!-- Footer -->
    <div style="border-top: 1px solid #ddd; padding-top: 10px; text-align: center; font-size: 11px; color: #777;">
        Generated by Techxle CRM | Consulting Services
    </div>
</div>
    """
    
    doc = frappe.get_doc("Print Format", pf_name)
    doc.html = html
    doc.save()

if __name__ == "__main__":
    setup()
